CREATE TABLE tbluseraccount(
	EMPLOYEE_ID VARCHAR(100) PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	ROLE_ID VARCHAR(50) NOT NULL,
	ACTIVE INT(1),
	PASSWORD_EXPIRY_DATE DATE NOT NULL,
	FAILED_LOGIN INT(1),
	LAST_FAILED_LOGIN DATE,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeeprofile(
	EMPLOYEE_ID VARCHAR(100) PRIMARY KEY,/
	USERNAME VARCHAR(50) NOT NULL,/
	FIRST_NAME VARCHAR(100) NOT NULL,/
	LAST_NAME VARCHAR(100) NOT NULL,/
	MIDDLE_NAME VARCHAR(100),/
	SUFFIX VARCHAR(5),/
	BIRTHDAY DATE NOT NULL,/
	EMPLOYMENT_STATUS INT(1),
	JOIN_DATE DATE,/
	EXIT_DATE DATE,/
	EXIT_REASON LONGTEXT,
	PROFILE_IMAGE VARCHAR(500),
	EMAIL VARCHAR(30) NOT NULL,
	PHONE VARCHAR(30),
	TELEPHONE VARCHAR(30),
    DEPARTMENT VARCHAR(20),
    BRANCH VARCHAR(20),
    DESIGNATION VARCHAR(20),/
    GENDER VARCHAR(20) NOT NULL,/
    ADDRESS VARCHAR(500) NOT NULL,
    HOURLY_RATE DOUBLE,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeeskills(
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	SKILL_ID VARCHAR(20) NOT NULL
);

CREATE TABLE tblskills(
	SKILL_ID VARCHAR(50) PRIMARY KEY,
	SKILL_DESC VARCHAR(200) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblrole(
	ROLE_ID VARCHAR(50) PRIMARY KEY,
	ROLE_DESC VARCHAR(100) NOT NULL,
	ACTIVE INT(1),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblrolepermission(
	ROLE_ID VARCHAR(50) NOT NULL,
	PERMISSION_ID INT(20) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblroleuser(
	ROLE_ID VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblcompany(
	COMPANY_ID VARCHAR(50) PRIMARY KEY,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEPHONE VARCHAR(20) NOT NULL,
	PHONE VARCHAR(20),
	TIMEZONE VARCHAR(20),
	COMPANY_LOGO VARCHAR(1000),
	LOGIN_BACKGROUND VARCHAR(1000),
	ICON VARCHAR(1000),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpage(
	PAGE_ID INT(50) PRIMARY KEY,
	PAGE_NAME VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpermission(
	PERMISSION_ID INT(50) PRIMARY KEY,
	PAGE_ID INT(50) NOT NULL,
	PERMISSION_DESC VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbluserlogs
( 
	USERNAME VARCHAR(50) NOT NULL,
	LOG_TYPE VARCHAR(100) NOT NULL,
	LOG_DATE DATE NOT NULL,
	LOG_TIME VARCHAR(15) NOT NULL,
	LOG VARCHAR(4000)
);

CREATE TABLE tblsystemcode(
	SYSTEM_TYPE VARCHAR(20) NOT NULL,
	SYSTEM_CODE VARCHAR(20) NOT NULL,
	SYSTEM_DESC VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblsystemparameters(
	PARAMETER_ID INT PRIMARY KEY,
	PARAMETER_DESC VARCHAR(100) NOT NULL,
	PARAMETER_EXTENSION VARCHAR(10),
	PARAMETER_NUMBER INT,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblcountry(
	COUNTRY_ID INT PRIMARY KEY,
	COUNTRY_NAME VARCHAR(300) NOT NULL,
	ISO3 VARCHAR(5),
	ISO2 VARCHAR(5),
	PHONE_CODE VARCHAR(20),
	CAPITAL VARCHAR(200),
	CURRENCY VARCHAR(5),
	CURRENCY_SYMBOL VARCHAR(5),
	TLD VARCHAR(5),
	NATIVE VARCHAR(100),
	REGION VARCHAR(50),
	SUB_REGION VARCHAR(50),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblstate(
	STATE_ID INT PRIMARY KEY,
	STATE_NAME VARCHAR(300) NOT NULL,
	COUNTRY_ID INT,
	COUNTRY_CODE VARCHAR(5),
	STATE_CODE VARCHAR(5),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblcity(
	CITY_ID INT PRIMARY KEY,
	CITY_NAME VARCHAR(300) NOT NULL,
	STATE_ID INT,
	STATE_CODE VARCHAR(5),
	COUNTRY_ID INT,
	COUNTRY_CODE VARCHAR(5),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	RECORD_LOG VARCHAR(100)
);

INSERT INTO tbluseraccount (EMPLOYEEID, USERNAME, PASSWORD, ACTIVE, PWEXPDT, FAILEDLOGIN) VALUES ('ADMIN', 'ADMIN', 'e672f48272c3f6d9', 1, '2021-12-30', 0);
INSERT INTO tblemployeeprofile (EMPLOYEEID, USERNAME, FILEAS, FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('ADMIN', 'ADMIN', 'AGULTO, LAWRENCE DE VERA', 'LAWRENCE', 'AGULTO', 'DE VERA');
INSERT INTO tblsystemcode (SYSTEM_TYPE, SYSTEM_CODE, SYSTEM_DESC) VALUES ('SYSTYPE', 'SYSTYPE', 'SYSTEM CODE');
INSERT INTO tblsystemparameters (PARAMETER_ID, PARAMETER_DESC, PARAMETER_EXTENSION, PARAMETER_NUMBER) VALUES ('1', 'SYSTEM PARAMETER', '', '1');
INSERT INTO tblemployeeprofile (EMPLOYEE_ID, USERNAME, FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER) VALUES ('ADMIN', 'ADMIN', 'LAWRENCE', 'AGULTO', 'DE VERA', 'MALE');

CREATE TABLE tblcompany(
	COMPANY_ID INT PRIMARY KEY,
	COMPANY_NAME VARCHAR(300) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PHONE VARCHAR(30),
	TELEPHONE VARCHAR(30) NOT NULL,
	WEBSITE VARCHAR(100),
	ADDRESS VARCHAR(500) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblapplicationsettings(
	SETTINGS_ID INT PRIMARY KEY,
	LOGIN_BG VARCHAR(500),
	LOGO_LIGHT VARCHAR(500),
	LOGO_DARK VARCHAR(500),
	LOGO_ICON_LIGHT VARCHAR(500),
	LOGO_ICON_DARK VARCHAR(500),
	FAVICON VARCHAR(500),
	CURRENCY VARCHAR(30) NOT NULL,
	TIMEZONE VARCHAR(100) NOT NULL,
	DATE_FORMAT VARCHAR(10) NOT NULL,
	TIME_FORMAT VARCHAR(10) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

INSERT INTO tblcompany (COMPANY_ID, COMPANY_NAME, EMAIL, TELEPHONE, ADDRESS, CURRENCY, ) VALUES ('COMP1', 'Worknest', 'worknest@gmail.com', '0898198877', '237 San Juan Accfa, Cabanatuan City, Nueva Ecija', 'PHP');

CREATE TABLE tbldepartment(
	DEPARTMENT_ID VARCHAR(50) PRIMARY KEY,
	DEPARTMENT VARCHAR(200),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldesignation(
	DESIGNATION_ID VARCHAR(50) PRIMARY KEY,
	DESIGNATION VARCHAR(200),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblbranch(
	BRANCH_ID VARCHAR(50) PRIMARY KEY,
	BRANCH VARCHAR(200),
	EMAIL VARCHAR(30) NOT NULL,
	PHONE VARCHAR(30),
	TELEPHONE VARCHAR(30),
    ADDRESS VARCHAR(500) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblholiday(
	HOLIDAY_ID VARCHAR(50) PRIMARY KEY,
	HOLIDAY VARCHAR(200) NOT NULL,
	HOLIDAY_DATE DATE NOT NULL,
	HOLIDAY_TYPE VARCHAR(20) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblleavetype(
	LEAVE_TYPE_ID VARCHAR(50) PRIMARY KEY,
	LEAVE_NAME VARCHAR(100) NOT NULL,
	NO_LEAVES INT,
	PAID_STATUS VARCHAR(20) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblleaveentitlement(
	LEAVE_ENTITLEMENT_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	LEAVE_TYPE VARCHAR(50) NOT NULL,
	NO_LEAVES INT,
	ACQUIRED_NO_LEAVES INT,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblleave(
	LEAVE_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	LEAVE_TYPE VARCHAR(50) NOT NULL,
	LEAVE_DATE DATETIME NOT NULL,
	START_TIME VARCHAR(10),
	END_TIME VARCHAR(10),
	REASON VARCHAR(500),
	STATUS INT(1),
	DECISION_DATE DATE,
	REJECTION_REASON VARCHAR(500),
	DECISION_BY VARCHAR(50),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeedocument(
	DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	DOCUMENT_NAME VARCHAR(100) NOT NULL,
	DOCUMENT_PATH VARCHAR(200) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblattendancerecord(
	ATTENDANCE_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	TIME_IN_DATE DATE NOT NULL,
	TIME_IN VARCHAR(10) NOT NULL,
	TIME_IN_BY VARCHAR(50),
	TIME_IN_IP VARCHAR(20),
	TIME_IN_LAT DOUBLE,
	TIME_IN_LONG DOUBLE,
	TIME_OUT_DATE DATE,
	TIME_OUT VARCHAR(10),
	TIME_OUT_BY VARCHAR(50),
	TIME_OUT_IP VARCHAR(20),
	TIME_OUT_LAT DOUBLE,
	TIME_OUT_LONG DOUBLE,
	REMARKS VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeededuction(
	DEDUCTION_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL, /
	DEDUCTION_TYPE VARCHAR(50) NOT NULL, /
	DEDUCTION_DATE DATE NOT NULL, /
	DEDUCTION_AMOUNT DOUBLE NOT NULL, /
	REOCCURRING INT, 
	RECURRENCE_PATTERN VARCHAR(50),
	RECURRENCE INT,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldeductiontype(
	DEDUCTION_TYPE_ID VARCHAR(50) PRIMARY KEY,
	DEDUCTION VARCHAR(200) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldeductionamount(
	DEDUCTION_TYPE_ID VARCHAR(50),
	START_RANGE DOUBLE NOT NULL,
	END_RANGE DOUBLE NOT NULL,
	DEDUCTION_AMOUNT DOUBLE NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblallowancetype(
	ALLOWANCE_TYPE_ID VARCHAR(50) PRIMARY KEY,
	ALLOWANCE VARCHAR(200) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblotherincometype(
	OTHER_INCOME_TYPE_ID VARCHAR(50) PRIMARY KEY,
	OTHER_INCOME VARCHAR(200) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpayrollspec (
	SPEC_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	SPEC_TYPE VARCHAR(20) NOT NULL,
	STATUS INT(1) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	SPEC_AMOUNT DOUBLE NOT NULL,
	PAYROLL_DATE DATE NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeesuperior (
	EMPLOYEE_ID VARCHAR(100) PRIMARY KEY,
	SUPERIOR_ID VARCHAR(20) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemployeesubordinate (
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	SUBORDINATE_ID VARCHAR(20) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbllocation(
	RECORD_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	LOCATION_DATE DATE NOT NULL,
	LOCATION_TIME VARCHAR(10) NOT NULL,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	REMARKS VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblnotificationsetting(
	NOTIFICATION_ID INT(50) PRIMARY KEY,
	NOTIFICATION VARCHAR(100) NOT NULL,
	ACTIVE INT(1),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblmailconfig(
	MAIL_ID INT(50) PRIMARY KEY,
	MAIL_HOST VARCHAR(100) NOT NULL,
	PORT INT NOT NULL,
	SMTP_AUTH INT(1) NOT NULL,
	SMTP_AUTO_TLS INT(1) NOT NULL,
	USERNAME VARCHAR(200) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	MAIL_ENCRYPTION VARCHAR(20),
	MAIL_FROM_NAME VARCHAR(200),
	MAIL_FROM_EMAIL VARCHAR(200),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpayroll(
	PAYROLL_ID INT(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	PAYROLL_START_DATE DATE NOT NULL,
	PAYROLL_END_DATE DATE NOT NULL,
	NO_HOURS DOUBLE,
	GROSS DOUBLE,
	NET DOUBLE,
	DEDUCTIONS DOUBLE,
	ALLOWANCE DOUBLE,
	OTHER_INCOME DOUBLE,
	GENERATED_DATE DATE NOT NULL,
	GENERATED_BY VARCHAR(50) NOT NULL,
	REMARKS VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblofficeshift(
	OFFICE_SHIFT_ID INT(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	DTR_DAY INT(1),
	DAY_OFF INT(1),
	TIME_IN VARCHAR(10),
	TIME_OUT VARCHAR(10),
	LATE_MARK INT(10),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpayrollgroup(
	PAYROLL_GROUP_ID VARCHAR(50) PRIMARY KEY,
	PAYROLL_GROUP_DESC VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblpayrollgroupemployee(
	PAYROLL_GROUP_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblattendanceadustment(
	ADJUSTMENT_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	ATTENDANCE_ID VARCHAR(50) NOT NULL,
	TIME_IN_ADJ VARCHAR(10) NOT NULL,
	TIME_OUT_DATE_ADJ DATE,
	TIME_OUT_ADJ VARCHAR(10),
	STATUS INT(1) NOT NULL,
	ATTACHMENT VARCHAR(500),
	REASON VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbltelephonelogsheet(
	LOG_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	INITIAL_CALL_DATE DATE,
	INITIAL_CALL_TIME VARCHAR(10),
	ACTUAL_CALL_DATE DATE,
	ACTUAL_CALL_TIME VARCHAR(10),
	ACTUAL_CALL_DURATION DOUBLE,
	RECIPIENT VARCHAR(300),
	TELEPHONE VARCHAR(30),
	REQUEST_DATE DATE,
	REQUEST_TIME VARCHAR(10),
	STATUS INT(1) NOT NULL,
	DECISION_DATE DATE,
	DECISION_TIME VARCHAR(10),
	DECISION_BY VARCHAR(100),
	REASON VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocument(
	DOCUMENT_ID VARCHAR(50) NOT NULL,
	DOCUMENT_NAME VARCHAR(500) NOT NULL,
	AUTHOR VARCHAR(100) NOT NULL,
	DEPARTMENT VARCHAR(50) NOT NULL,
	DOCUMENT_PATH VARCHAR(500) NOT NULL,
	DOCUMENT_CATEGORY VARCHAR(50) NOT NULL,
	DOCUMENT_EXTENSION VARCHAR(10) NOT NULL,
	DOCUMENT_SIZE DOUBLE,
	DESCRIPTION VARCHAR(500) NOT NULL,
	UPLOAD_DATE DATE,
	UPLOAD_TIME VARCHAR(10),
	PUBLISH INT(1) NOT NULL,
	PUBLISH_BY VARCHAR(100),
	PUBLISH_DATE DATE,
	PUBLISH_TIME VARCHAR(10),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocumentsettings(
	SETTINGS_ID INT PRIMARY KEY,
	MAX_FILE_SIZE DOUBLE,
	AUTHORIZATION INT(1),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocumentfiletype(
	SETTINGS_ID INT,
	FILE_TYPE VARCHAR(50) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocumentauthorizer(
	DEPARTMENT VARCHAR(50),
	AUTHORIZER VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocumentdepartmentpermission(
	DOCUMENT_ID VARCHAR(50) NOT NULL,
	DEPARTMENT_ID VARCHAR(50) NOT NULL,
	PERMISSION VARCHAR(1) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbldocumentemployeepermission(
	DOCUMENT_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	PERMISSION VARCHAR(1) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbltrasmittal(
	TRANSMITTAL_ID VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	STATUS INT(1),
	CURRENT_EMPLOYEE VARCHAR(100) NOT NULL,
	CURRENT_DEPARTMENT VARCHAR(50) NOT NULL,
	TRANSMITTED_EMPLOYEE VARCHAR(100) NOT NULL,
	TRANSMITTED_DEPARTMENT VARCHAR(50) NOT NULL,
	LAST_TRANSACTION_DATE DATE,
	LAST_TRANSACTION_TIME VARCHAR(10),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbltrasmittalhistory(
	HISTORY_ID VARCHAR(50) NOT NULL,
	TRANSMITTAL_ID VARCHAR(50),
	TRASMITTAL_TYPE INT(1),
	EMPLOYEE_FROM VARCHAR(100) NOT NULL,
	DEPARTMENT_FROM VARCHAR(50) NOT NULL,
	EMPLOYEE_TO VARCHAR(100) NOT NULL,
	DEPARTMENT_TO VARCHAR(50) NOT NULL,
	TRANSACTION_DATE DATE,
	TRANSACTION_TIME VARCHAR(10),
	RECEIVED_BY VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblstw(
	STW_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	STATUS INT(1),
	FILE_PATH VARCHAR(500),
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	REASON VARCHAR(500) NOT NULL,
	BENEFITS VARCHAR(1000) NOT NULL,
	POST_DATE DATE,
	POST_TIME VARCHAR(10),
	DECISION_DATE DATE,
	DECISION_TIME VARCHAR(10),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblstwvote(
	VOTE_ID VARCHAR(50) PRIMARY KEY,
	STW_ID VARCHAR(50),
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	SATISFACTION INT,
	QUALITY INT,
	INNOVATION INT,
	FEASIBILITY INT,
	TOTAL INT,
	VOTE_DATE DATE,
	VOTE_TIME VARCHAR(10),
	REMARKS VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblstwvotesummary(
	STW_ID VARCHAR(50),
	SATISFACTION DOUBLE,
	QUALITY DOUBLE,
	INNOVATION DOUBLE,
	FEASIBILITY DOUBLE,
	TOTAL DOUBLE,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbltrainingroomlogsheet(
	LOG_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	START_DATE DATE NOT NULL,
	START_TIME VARCHAR(10) NOT NULL,
	END_DATE DATE NOT NULL,
	END_TIME VARCHAR(10) NOT NULL,
	REQUEST_DATE DATE NOT NULL,
	REQUEST_TIME VARCHAR(10) NOT NULL,
	STATUS INT(1) NOT NULL,
	DECISION_DATE DATE,
	DECISION_TIME VARCHAR(10),
	DECISION_BY VARCHAR(100),
	REASON VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tbltrainingroomparticipant(
	LOG_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblemailrecipient(
	RECIPIENT_ID INT(50) PRIMARY KEY,
	NOTIFICATION_ID VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblwcf(
	WCF_ID VARCHAR(50) PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	DEPARTMENT VARCHAR(50) NOT NULL,
	STATUS INT(1) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	APPROVAL_DATE DATE,
	APPROVAL_TIME VARCHAR(10),
	APPROVAL_BY VARCHAR(100),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblwcfparticulars(
	PARTICULAR_ID VARCHAR(50) PRIMARY KEY,
	WCF_ID VARCHAR(50) NOT NULL,
	DETAILS VARCHAR(100) NOT NULL,
	WCF_TYPE VARCHAR(50) NOT NULL,
	MONDAY DOUBLE,
	TUESDAY DOUBLE,
	WEDNESDAY DOUBLE,
	THURSDAY DOUBLE,
	FRIDAY DOUBLE,
	TOTAL DOUBLE,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblticket(
	TICKET_ID VARCHAR(50) PRIMARY KEY,
	REQUESTER VARCHAR(100) NOT NULL,
	DEPARTMENT VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	ASSIGNED_DEPARTMENT VARCHAR(50) NOT NULL,
	ASSIGNED_EMPLOYEE VARCHAR(100) NOT NULL,
	SUBJECT VARCHAR(200) NOT NULL,
	DESCRIPTION VARCHAR(1000) NOT NULL,
	PRIORITY INT(1) NOT NULL,
	STATUS INT(1) NOT NULL,
	DUE_DATE DATE NOT NULL,
	CREATED_DATE DATE NOT NULL,
	CREATED_TIME VARCHAR(10) NOT NULL,
	ACCEPTED_DATE DATE,
	ACCEPTED_TIME VARCHAR(10),
	SOLVED_DATE DATE,
	SOLVED_TIME VARCHAR(10),
	CLOSED_DATE DATE,
	CLOSED_TIME VARCHAR(10),
	DECISION_DATE DATE,
	DECISION_TIME VARCHAR(10),
	REJECTION_REASON VARCHAR(500),
	CANCELLATION_REASON VARCHAR(500),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblticketattachment(
	ATTACHMENT_ID VARCHAR(50) PRIMARY KEY,
	TICKET_ID VARCHAR(50),
	FILE_NAME VARCHAR(500),
	FILE_PATH VARCHAR(500),
	UPLOAD_BY VARCHAR(100) NOT NULL,
	UPLOAD_DATE DATE NOT NULL,
	UPLOAD_TIME VARCHAR(10) NOT NULL,
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblticketnotes(
	NOTE_ID VARCHAR(50) PRIMARY KEY,
	TICKET_ID VARCHAR(50),
	NOTE_BY VARCHAR(100) NOT NULL,
	NOTE VARCHAR(1000) NOT NULL,
	NOTE_DATE DATE,
	NOTE_TIME VARCHAR(10),
	RECORD_LOG VARCHAR(100)
);

CREATE TABLE tblticketadjustment(
	ADJUSTMENT_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	TICKET_ID VARCHAR(50) NOT NULL,
	STATUS INT(1) NOT NULL,
	ASSIGNED_EMPLOYEE_ORG VARCHAR(100) NOT NULL,
	ASSIGNED_EMPLOYEE_ADJ VARCHAR(100) NOT NULL,
	CATEGORY_ORG VARCHAR(50) NOT NULL,
	CATEGORY_ADJ VARCHAR(50) NOT NULL,
	SUBJECT_ORG VARCHAR(200) NOT NULL,
	SUBJECT_ADJ VARCHAR(200) NOT NULL,
	DESCRIPTION_ORG VARCHAR(1000) NOT NULL,
	DESCRIPTION_ADJ VARCHAR(1000) NOT NULL,
	PRIORITY_ORG INT(1) NOT NULL,
	PRIORITY_ADJ INT(1) NOT NULL,
	DUE_DATE_ORG DATE NOT NULL,
	DUE_DATE_ADJ DATE NOT NULL,
	REASON VARCHAR(500),
	REQUEST_DATE DATE,
	REQUEST_TIME VARCHAR(10),
	DECISION_DATE DATE,
	DECISION_TIME VARCHAR(10),
	DECISION_BY VARCHAR(100),
	RECORD_LOG VARCHAR(100)
);